//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-12-03 09:26:50
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("AgentInfos")]
    public partial class AgentInfos
    {

	   /// <summary>
     	/// 
     	/// </summary>
		[ExplicitKey]
		public string DeptCode { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Company { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string AgentID { get; set; }

		   
    }
}

