
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-12-17 09:49:05
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("AgentInputs")]
    public partial class AgentInputs
    {

	   
/// <summary>
     	/// 
     	/// </summary>
	
	[Key]
	
	public int Id { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CardID { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Name { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Sex { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Nation { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? Birthday { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string HomeAddress { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Authority { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ValidDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ExpirationDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Phone { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Marriage { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Handedness { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string HouseholdType { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Diploma { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Major { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? EduStart { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? EduEnd { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string School { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string HomeContact { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string PostalCode { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string HomeTel { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string EmergentContact { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string EmergentPhone { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string PoliticalStatus { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ContractExpDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string BatchCode { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string AgentID { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? CreateDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CreateUser { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ModifyDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string ModifyUser { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Department { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public bool? IsStop { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public bool? IsInterview { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public bool? IsHealthExam { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public bool? IsCard { get; set; }

		   
    }
}

