//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2021-01-04 11:42:50
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("BusDivisions")]
    public partial class BusDivisions
    {

	   /// <summary>
     	/// 
     	/// </summary>
		public string id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string img { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime? CreateTime { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Statu { get; set; }

		   
    }
}

