
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-12-22 13:35:50
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("BusRoute")]
    public partial class BusRoute
    {

	   
/// <summary>
     	/// 
     	/// </summary>
	
	[Key]
	
	public int Id { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string LineName { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string LineItem { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string StationName { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string busLoc { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string DayTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string NightTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? CreateTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CreateUser { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ModifyDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string ModifyUser { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public bool? IsStop { get; set; }

		   
    }
}

