
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-12-24 18:34:51
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("CheckIn")]
    public partial class CheckIn
    {

	   
/// <summary>
     	/// 
     	/// </summary>
	
	[ExplicitKey]
	
	public string RoomId { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string RoomNo { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string RoomType { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string RoomUse { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string UserId { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string UserName { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Department { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Sex { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Position { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CostCenter { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? CheckInTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string PhoneNumber { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string OrgCode { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string IsUsed { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? DimissionTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? CreateTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CreateUser { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Remark { get; set; }

		   
    }
}

