
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-10-27 14:22:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("HR_CardID")]
    public partial class HR_CardID
    {

	   
/// <summary>
     	/// 
     	/// </summary>
	
	[ExplicitKey]
	
	public string CardID { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ReadCardTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string UserName { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Sex { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Nation { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? Birthdate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string HomeAddress { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Authority { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ValidDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ExpirationDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Notes { get; set; }

		   
    }
}

