
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-10-27 14:22:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("HR_User")]
    public partial class HR_User
    {

	   
/// <summary>
     	/// 
     	/// </summary>
	
	[Key]
	
	public int Id { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string UserId { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string UserName { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ExpiryDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string PhoneNumber { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Remark { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ModifyTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public bool? IsSend { get; set; }

		   
    }
}

