
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-12-17 09:49:05
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("HRInputs")]
    public partial class HRInputs
    {

	   
/// <summary>
     	/// 
     	/// </summary>
	
	[Key]
	
	public int Id { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CardID { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Name { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string PersonnelArea { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string PersonnelSubArea { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string WorkerGroup { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string WokerSubGroup { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string SalaryArea { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Occupation { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string RankCode { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string RecruitmentSource { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CommunicationType { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? EndDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string ContractType { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Probation { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string FireNotePeriod { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string ResignNotePeriod { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string RecruitmentWay { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string EmpolyeeType { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ModifyDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string ModifyUser { get; set; }

		   
    }
}

