
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-12-17 09:33:09
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace GMS.Model
{	
   
   [Table("Interview")]
    public partial class Interview
    {

	   
/// <summary>
     	/// 
     	/// </summary>
	
	[Key]
	
	public int Id { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CardID { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Name { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Department { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string InterviewResult { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string Interviewer { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? CreateTime { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string CreateUser { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public DateTime? ModifyDate { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public string ModifyUser { get; set; }

		
/// <summary>
     	/// 
     	/// </summary>
	
	public bool? IsStop { get; set; }

		   
    }
}

