//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-11-06 11:19:12
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------


using GMS.Model;
using GMS.DAL;

namespace GMS.BLL
{	
	public partial class BatchesBLL:BaseServiceDapperContrib<Model.Batches>
    {
     

    }
}

